### ISSUE TITLE
Explore other options for 'awakened' familiars

### ISSUE THREAD

**Issue by khawley** [khawley/fr_familiars#5]
instead of removing a familiar that has awakened and attaching the next in the list - 
have options to:
- do nothing (leave equipped)
- unequip only
- unequip & grab the next one

and _always_ print out a list of the awakened familiars, and which dragon they were originally equipped to.

**Comment by elzilrac** [comment]
:ship:

**Comment by khawley** [comment]
Updated in v1.1.  As the ReadMe explains, there are 2 new optional variables that can be passed into `PetFamiliars` that allows more flexibility and specificity to handling awakened familiars.
