### ISSUE TITLE
BUG- cannot run new install of script

### ISSUE THREAD

**Issue by elzilrac** [khawley/fr_familiars#9]
```
Traceback (most recent call last):
  File "pet_my_familiars.py", line 31, in <module>
    DRAGON_LIST = D.get_list()
  File "~/fr_familiars/fr_interactions/DragonLair.py", line 56, in get_list
    if not self.__parse_lair_page(html):
  File "~/fr_familiars/fr_interactions/DragonLair.py", line 79, in __parse_lair_page
    if i.text])
ValueError: max() arg is an empty sequence
```

**Comment by khawley** [comment]
@elzilrac I'm pretty sure this is a result of not being logged/the cookie having gone bad.  I don't have logic in place for that overall.  But, at least now, you can still get your dragons & their equipped familiars without being logged in.  No more error message

**Comment by elzilrac** [comment]
Hmn, it's a fresh cookie- grabbed it literally minutes before I ran it. And
the read bestiary worked. But I'll try again with a fresh cookie soon.
